### Create customer
POST {{baseUrl}}/api/customers
Content-Type: application/json
Accept: application/json

{
  "name": "Test Customer",
  "dateOfBirth": "1980-08-09",
  "emailAddress": "test@gmail.com"
}

> {%
  client.global.set("customerId", response.body.id);
%}

### List customers
GET {{baseUrl}}/api/customers
Accept: application/json

### Get customer by id
GET {{baseUrl}}/api/customers/{{customerId}}
Accept: application/json

### Update customer
PUT {{baseUrl}}/api/customers/{{customerId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Ada Lovelace",
  "dateOfBirth": "1986-08-13",
  "emailAddress": "ada.lovelace@example.com"
}

### Delete customer
DELETE {{baseUrl}}/api/customers/{{customerId}}
Accept: application/json
